name: Dev Pull Request
on:
  pull_request:
    branches:
      - dev
    paths:
      - '**.py'
      - '**.yml'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_FILE: '.github/workflows/dev-pr.yml'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    # https://www.peterbe.com/plog/install-python-poetry-github-actions-faster
    - name: Load cached ~/.local
      uses: actions/cache@v4
      with:
        path: ~/.local
        key: dotlocal-${{ runner.os }}-${{ hashFiles(env.WORKFLOW_FILE) }}

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Load cached venv
      id: cache-virtualenv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles(env.WORKFLOW_FILE) }}

    - name: Install poetry dependencies
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      run: poetry install

    - name: Run Tests
      run: |
        poetry run python manage.py test --no-input
