name: Dev Push
on:
  push:
    branches:
      - dev
    paths:
      - '**.py'
      - '**.yml'
      - 'poetry.lock'
      - 'pyproject.toml'

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_FILE: '.github/workflows/dev.yml'
      AWS_DEFAULT_REGION: 'us-west-2'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: ‘2’

    - name: Install poetry
      run: pipx install poetry

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
        cache: 'poetry'
        cache-dependency-path: poetry.lock

    - name: Load cached venv
      id: cache-virtualenv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles(env.WORKFLOW_FILE) }}
        restore-keys: venv-${{ runner.os }}-

    - name: Install poetry dependencies
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      run: poetry install

    - name: Run Tests and Generate Coverage Report
      run: |
        poetry run coverage run -m unittest
        poetry run coverage xml

    - name: Upload Coverage Report to Codecov
      uses: codecov/codecov-action@v4.0.1
      with:
        files: coverage.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos

    - name: Checkout Main Branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Reset main branch
      run: |
        git fetch origin dev:dev
        git reset --hard dev

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: main-promotion
        delete-branch: true
        title: Promote dev to main branch
