name: Dev Push
on:
  push:
    branches:
      - dev
    paths:
      - '**.py'
      - '**.yml'

jobs:
  main:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_FILE: '.github/workflows/dev.yml'
    steps:
    - name: Get workflow file relative path
      env:
        WORKFLOW_REF: ${{ github.workflow_ref }}
        REPO: ${{ github.repository }}/
      id: wf_rel_path
      run: |
           echo "abs_path=${WORKFLOW_REF%%@*}"
           echo "path=${abs_path#"${REPO}"}" >> $GITHUB_OUTPUT
           cat $GITHUB_OUTPUT

    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: ‘2’

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.12

    # https://www.peterbe.com/plog/install-python-poetry-github-actions-faster
    - name: Load cached ~/.local
      uses: actions/cache@v4
      with:
        path: ~/.local
        key: dotlocal-${{ runner.os }}-${{ hashFiles(steps.wf_rel_path.outputs.path) }}

    - name: Install poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Load cached venv
      id: cache-virtualenv
      uses: actions/cache@v4
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}-${{ hashFiles(steps.wf_rel_path.outputs.path) }}

    - name: Install poetry dependencies
      if: steps.cache-virtualenv.outputs.cache-hit != 'true'
      run: poetry install

    - name: Run Tests and Generate Coverage Report
      run: |
        poetry run coverage run -m unittest
        poetry run coverage xml

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4-beta
      with:
        files: coverage.xml
        fail_ci_if_error: true
        token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos

    - name: Checkout Main Branch
      uses: actions/checkout@v4
      with:
        ref: main

    - name: Reset main branch
      run: |
        git fetch origin dev:dev
        git reset --hard dev

    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v6
      with:
        branch: main-promotion
        delete-branch: true
        title: Promote dev to main branch
