name: Production Build and Publish
on:
  push:
    branches:
      - main
    paths:
      - '**.py'
      - '**.yml'
      - 'poetry.lock'
      - 'pyproject.toml'

jobs:
  buildAndPublish:
    runs-on: ubuntu-latest
    env:
      WORKFLOW_FILE: '.github/workflows/production.yml'
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: ‘2’

    - name: Install Poetry, Install Dependencies, Build Project, and Publish to Pypi
      uses: JRubics/poetry-publish@v2.0
      with:
        pypi_token: ${{ secrets.PYPI_TOKEN }}
